name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  container-build:
    name: Container Image Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Buildah Action
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: gpu-jupyter-alphafold
          tags: latest
          containerfiles: |
            ./Containerfile
